# Artifact coordinates
group=games.alejandrocoria
version=0.1.0-SNAPSHOT
artifactId=mapfrontiers-api

# Toolchain
javaVersion=17

# POM metadata
pomName=MapFrontiers API
pomDescription=Public Java API for MapFrontiers plugins and integrations.
pomUrl=https://github.com/alejandrocoria/MapFrontiers-API

pomLicenseName=MIT License
pomLicenseUrl=https://opensource.org/license/mit

pomDeveloperId=alejandrocoria
pomDeveloperName=Alejandro Coria
pomDeveloperEmail=contact@alejandrocoria.games

pomScmConnection=scm:git:https://github.com/alejandrocoria/MapFrontiers-API.git
pomScmDeveloperConnection=scm:git:ssh://git@github.com/alejandrocoria/MapFrontiers-API.git
pomScmUrl=https://github.com/alejandrocoria/MapFrontiers-API

# Gradle runtime
org.gradle.jvmargs=-Xmx3G
